version: 2.1

executors:
  android_executor:
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: "-Xmx3200m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      TERM: dumb
    working_directory: ~/workspace

commands:
  restore_workspace:
    description: Restore Workspace
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - restore_cache:
          keys:
            - gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "buildSrc/src/main/java/Config.kt" }}
  save_workspace:
    description: Save Workspace
    steps:
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - ./*/build

jobs:
  build:
    executor: android_executor
    steps:
      - restore_workspace
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - run:
          name: Build Debug APK and Bundle
          command: ./gradlew assembleDebug bundleDebug
      - store_artifacts:
          path: app/build/outputs
          destination: outputs
      - save_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - ~/.gradle/wrapper/
      - save_cache:
          key: gradle-cache-{{ checksum "buildSrc/src/main/java/Config.kt" }}
          paths:
            - ~/.gradle/caches/
      - save_workspace
  build_release:
    executor: android_executor
    steps:
      - restore_workspace
      - run:
          name: Build Release APK and Bundle
          command: ./gradlew assembleRelease bundleRelease
      - store_artifacts:
          path: app/build/outputs
          destination: outputs
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - save_workspace
  check:
    executor: android_executor
    steps:
      - restore_workspace
      - run:
          name: Check App and Dependencies
          command: ./gradlew detektAll spotlessCheck dependencyUpdates
      - store_artifacts:
          path: build/reports/detekt
          destination: detekt
      - store_artifacts:
          path: build/dependencyUpdates
          destination: dependencyUpdates
      - save_workspace

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      #- build_release:
      #    requires:
      #      - build
      - check:
          requires:
            - build